---
- hosts: default

  vars:
    container: true
    mysql_root_password: id3636mysql
    tomcat_admin:
      user: admin
      password: tc3636
    mysql_credentials:
      user: localidxadm
      password: localidxadmpass
    lui_version: v0.12

  tasks:
    - name: Clone lui-solr repo into development tree
      connection: local
      git: repo=ssh://git.indexdata.com:222/home/git/pub/lui-solr dest=./lui-solr version={{ lui_version }} accept_hostkey=yes
      when: not container

    - name: Create deployment environment
      become: yes
      file: path={{ item }} state=directory
      with_items:
        - /usr/share/masterkey/lui
        - /var/lib/masterkey/lui/solr/lui
        - /var/log/masterkey/lui
        - /etc/masterkey/lui
        - /var/log/masterkey/harvester
        - /etc/masterkey/harvester
      when: not container

    - name: Install prerequisites from apt
      become: yes
      apt:
        update-cache: yes
        name:
          - python-apt
          - python-pip
          - python-virtualenv
          - apt-transport-https
          - ca-certificates
          - openjdk-8-jdk
          - tomcat8
          - tomcat8-admin
          - mysql-server
          - python-mysqldb
          - maven 

    - name: Install Docker prerequisites from apt
      become: yes
      apt:
        update-cache: yes
        name:
          - python-pip
          - python-virtualenv
      when: container

    - name: Install docker-compose
      become: yes
      pip:
        name: docker-compose
      when: container

    - name: add Docker gpg key
      become: yes
      apt_key: url=https://download.docker.com/linux/debian/gpg
      when: container

    - name: add Docker apt repo
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
      when: container

    - name: Install Docker
      become: yes
      apt:
        name: docker-ce
        update_cache: yes
      when: container

    - name: Create tomcat administrative user
      become: yes
      lineinfile: dest=/etc/tomcat8/tomcat-users.xml insertbefore="</tomcat-users>" line={{ item }}
      with_items:
        - '  <role rolename="manager-gui"/>'
        - '  <user username="{{ tomcat_admin.user }}" password="{{ tomcat_admin.password }}" roles="manager-gui"/>'
      notify: Restart Tomcat
      when: not container

    - name: Update permissions on harvester directories
      become: yes
      file: path={{ item }} owner=tomcat8
      with_items:
        - /var/log/masterkey/harvester
      when: not container

    - name: Create lui-solr account
      become: yes
      user: name=lui-solr state=present system=yes home=/var/lib/masterkey/lui
      when: not container

    - name: Update permissions on lui-solr directories
      become: yes
      file: path={{ item }} owner=lui-solr recurse=yes
      with_items:
        - /var/lib/masterkey/lui
        - /var/log/masterkey/lui
      when: not container

    - name: Link Solr configuration
      become: yes
      file: src=/vagrant/lui-solr/conf/solr path=/etc/masterkey/lui/solr state=link
      when: not container

    - name: Link Solr defaults
      become: yes
      file: src=/etc/masterkey/lui/solr/lui-solr.in.sh path=/etc/default/lui-solr.in.sh state=link
      when: not container

    - name: Install Solr binary
      become: yes
      command: /vagrant/lui-solr/dist/install_solr6_service.sh /vagrant/lui-solr/dist/solr-6.1.0.tgz -d /var/lib/masterkey/lui -i /usr/share/masterkey/lui -s lui-solr -u lui-solr -f creates=/usr/share/masterkey/lui/solr-6.1.0
      when: not container

    - name: Remove extra files created by Solr install
      become: yes
      file: path={{ item }} state=absent
      with_items:
        - /var/lib/masterkey/lui/log4j.properties
        - /var/lib/masterkey/lui/logs
        - /var/lib/masterkey/lui/data
      when: not container

    - name: Start lui-solr service
      become: yes
      service: name=lui-solr state=started
      when: not container

    - name: Update MySQL root password
      become: yes
      mysql_user: name=root password={{ mysql_root_password }}

    - name: Update my.cnf
      become: yes
      copy:
        dest: /root/.my.cnf
        mode: 0600
        content: |
          [client]
          user=root
          password={{ mysql_root_password }}

    - name: configure mariadb to bind to all addresses
      become: yes
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: ^bind-address
        line: bind-address = 0.0.0.0
        state: present
        backup: yes
      when: container
      notify: Restart DB

    - name: Create localindices database
      become: yes
      mysql_db: name=localindices state=present

    - name: Create the mysql user
      become: yes
      mysql_user: name={{ mysql_credentials.user }} password={{ mysql_credentials.password }} priv="localindices.*:all" append_privs=yes state=present
      when: not container

    - name: Create the mysql user
      become: yes
      mysql_user: name={{ mysql_credentials.user }} password={{ mysql_credentials.password }} priv="localindices.*:all" append_privs=yes state=present host=%
      when: container

    # These tasks are not idempotent - they will zap all tables in the database

    # The "right way" - initialize the database, load alter scripts on top
    # Unfortunately, it fails
    # - name: Initialize the database
    #   become: yes
    #   mysql_db: name=localindices state=import target=/vagrant/sql/localindices.sql

    # - name: Collect the db alterations
    #   shell: "find /vagrant/sql/v*.* -name \"????-??-??.sql\" -print"
    #   register: db_alter

    # - name: Run the alteration scripts
    #   become: yes
    #   mysql_db: name=localindices state=import target={{ item }}
    #   with_items: "{{ db_alter.stdout_lines }}"

    # The "wrong way" - load a database from production
    # - name: Initialize the database
    #   become: yes
    #   mysql_db: name=localindices state=import target=/vagrant/sql/samples/localindices-katsu--2016-05-01_06-00-01.sql
    # Which didn't work, either.

    # Loading new schema 2.8-2.11
    - name: Initialize the database
      become: yes
      mysql_db: name=localindices state=import target=/vagrant/sql/schema.v2.8-with-sample-data.sql
      notify: Restart Tomcat

    - name: Load 2.9 table alteration
      become: yes
      mysql_db: name=localindices state=import target=/vagrant/sql/v2.9/2016-05-03.sql
      notify: Restart Tomcat

    - name: Load 2.10 table alteration
      become: yes
      mysql_db: name=localindices state=import target=/vagrant/sql/v2.10/2016-07-04.sql
      notify: Restart Tomcat

    - name: Load 2.11 table alteration
      become: yes
      mysql_db: name=localindices state=import target=/vagrant/sql/v2.11/2016-07-15.sql
      notify: Restart Tomcat

    - name: Load 2.11 table data
      become: yes
      mysql_db: name=localindices state=import target=/vagrant/sql/v2.11/v2.11-data.sql
      notify: Restart Tomcat

    - name: Load reshare table data
      become: yes
      mysql_db: name=localindices state=import target=/vagrant/sql/load-reshare-data-to-v2.11.sql
      notify: Restart Tomcat

    - name: Build Harvester and Harvester Admin web apps
      shell: mvn install > mvn-install.log creates=/vagrant/mvn-install.log chdir=/vagrant/
      notify: Restart Tomcat

    - name: Build and start Harvester/Harvester Admin containers
      become: yes
      docker_service:
        project_src: /vagrant

    - name: Link Harvester web app
      become: yes
      file: src=/vagrant/harvester/target/harvester path=/usr/share/masterkey/harvester state=link
      when: not container

    - name: Link Harvester configuration
      become: yes
      file: src=/vagrant/harvester/target/harvester/WEB-INF/harvester.properties path=/etc/masterkey/harvester/harvester.properties state=link
      when: not container

    - name: Link Harvester stylesheets
      become: yes
      file: src=/vagrant/harvester/target/harvester/WEB-INF/stylesheets/{{ item }} path=/var/lib/tomcat8/{{ item }} state=link
      with_items:
        - ARTstor-electronic-url-fix.xsl
        - addmergekey.xsl
        - addsnippet.xsl
        - creator-filter-date-2.0.xsl
        - dc-lexis.xsl
        - marc21.xsl
        - oai2marc.xsl
        - oai_dc.xsl
        - oaipmh-dc_pazpar2-minimal.xsl
        - pz-author-remove-end-date.xsl
        - pz-subject-split.xsl
        - pz2-ourl-base.xsl
        - pz2-ourl-marc21.xsl
        - pz2-solr-split-1.0.xsl
        - pz2-solr-split-2-levels.xsl
        - pz2-solr.xsl
        - pz2index.xsl
        - snippet2pz.xsl
        - solr-subject-split.xsl
        - map-relator-to-contributor-type.xsl
      when: not container

    - name: Create Harvester cache directory
      become: yes
      file: path=/var/cache/harvester owner=tomcat8 group=adm state=directory
      when: not container

    - name: Provide access to Harvester test data
      become: yes
      lineinfile: dest=/etc/tomcat8/server.xml line="\t<Context docBase=\"/vagrant/harvester/test\" path=\"/test\" />" insertbefore="</Host>"
      notify: Restart Tomcat
      when: not container

    - name: Deploy Tomcat context fragment for Harvester
      become: yes
      file: src=/vagrant/etc/harvester-context.xml path=/etc/tomcat8/Catalina/localhost/harvester.xml state=link
      notify: Restart Tomcat
      when: not container

    - name: Link Harvester Admin web app
      become: yes
      file: src=/vagrant/harvester-admin/target/harvester-admin path=/usr/share/masterkey/harvester-admin state=link
      notify: Restart Tomcat
      when: not container

    - name: Deploy Tomcat context fragment for Harvester Admin
      become: yes
      file: src=/vagrant/etc/harvester-admin-context.xml path=/etc/tomcat8/Catalina/localhost/harvester-admin.xml state=link
      when: not container

  handlers:
    - name: Restart Tomcat
      become: yes
      service: name=tomcat8 state=restarted
      when: not container

    - name: Restart DB
      become: yes
      service: name=mysql state=restarted
