#%RAML 0.8
title: Harvester
version: 1.0
baseUri: http://harvester.example.com/harvester/records
documentation:
 - title: Overview
   content: >
     This API provides a means for clients to control a pool or
     harvesting tasks which are scheduled to run at specified times in
     order to maintain a live database of accumulated results.

/harvestables:
  get:
    description: >
      Return brief information about all harvesting jobs.
    responses:
      200:
        description: >
          A &lt;harvestables> document containing zero or more
          &lt;harvestableBrief> records, each of which carries
          information about a harvesting job. This information
          includes the &lt;currentStatus> field.
        body:
          text/xml:
            example: |
              <harvestables count="68" max="100" uri="http://localhost:8080/harvester/records/harvestables/" start="0">
                <harvestableBrief uri="http://localhost:8080/harvester/records/harvestables/6503/">
                  <amountHarvested>0</amountHarvested>
                  <currentStatus>WARN</currentStatus>
                  <enabled>false</enabled>
                  <id>6503</id>
                  <jobClass>OaiPmhResource</jobClass>
                  <lastHarvestFinished>2015-05-25T12:07:56Z</lastHarvestFinished>
                  <lastHarvestStarted>2015-05-25T12:07:56Z</lastHarvestStarted>
                  <lastUpdated>2015-05-25T12:07:56Z</lastUpdated>
                  <message>No Records matched</message>
                  <name>A OAI-PMH test</name>
                  <nextHarvestSchedule>2016-03-19T00:00:00Z</nextHarvestSchedule>
                </harvestableBrief>
                ...
              </harvestables>

  post:
    description: >
      Create a new harvesting job.
  /{id}:
    uriParameters:
      id:
        description: >
          Opaque identifier of a specific harvesting job.
    get:
      description: >
        Retrieve details about, and status of, a specific harvesting job.
    delete:
      description: >
        Remove a harvesting job, cancelling its current run if it's active.
    put:
      description: >
        Update details of the harvesting job. Doing this while the job
        is running will force the present run to be abandoned, and the
        harvest to be restarted.
