ALTER TABLE `HARVESTABLE` ADD COLUMN `FAILEDRECORDSLOGGING` TEXT;
ALTER TABLE `HARVESTABLE` ADD COLUMN `MAXSAVEDFAILEDRECORDSPERRUN` SMALLINT DEFAULT 100;
ALTER TABLE `HARVESTABLE` ADD COLUMN `MAXSAVEDFAILEDRECORDSTOTAL` SMALLINT DEFAULT 1000;

