#!/bin/sh -e 

ETC_DIR=/etc/masterkey/harvester-admin
if [ -h "${ETC_DIR}/web.xml" ] ; then 
  rm "${ETC_DIR}/web.xml" 
fi


dpkg-maintscript-helper mv_conffile \
               /usr/share/masterkey/harvester-admin/WEB-INF/web.xml /etc/masterkey/harvester-admin/web.xml 2.6.0-alpha4-1indexdata -- "$@"
dpkg-maintscript-helper mv_conffile \
               /usr/share/masterkey/harvester-admin/WEB-INF/harvester.properties /etc/masterkey/harvester-admin/harvester.properties 2.6.0-alpha4-1indexdata -- "$@"
dpkg-maintscript-helper mv_conffile \
               /usr/share/masterkey/harvester-admin/WEB-INF/classes/log4j.properties /etc/masterkey/harvester-admin/log4j.properties 2.6.0-alpha4-1indexdata -- "$@"
