
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `SETTING` WRITE;
/*!40000 ALTER TABLE `SETTING` DISABLE KEYS */;
INSERT INTO `SETTING` (`ID`, `NAME`, `LABEL`, `VALUE`) VALUES (1,'cf.engine.url.1','CF Engine (default)','http://connect.indexdata.com:9010/connector');
INSERT INTO `SETTING` (`ID`, `NAME`, `LABEL`, `VALUE`) VALUES (2,'cf.repo.url.1','CF Repo (default)','https://idtest:idtest36@cfrepo.indexdata.com/repo.pl/idtest/');
INSERT INTO `SETTING` (`ID`, `NAME`, `LABEL`, `VALUE`) VALUES (5552,'solr.searchables.cclmap_au','Author (CCL)','1=author_exact_au');
INSERT INTO `SETTING` (`ID`, `NAME`, `LABEL`, `VALUE`) VALUES (5553,'solr.searchables.cclmapTerm','Term (CCL)','1=text');
INSERT INTO `SETTING` (`ID`, `NAME`, `LABEL`, `VALUE`) VALUES (5554,'solr.searchables.cclmapOther','New Setting','1=newvalue');
INSERT INTO `SETTING` (`ID`, `NAME`, `LABEL`, `VALUE`) VALUES (5602,'openaccess.searchables.test','OpenAccess','Test');
/*!40000 ALTER TABLE `SETTING` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

